apiVersion: v1
kind: Secret
metadata:
  name: postgres-credentials
type: Opaque
data:
  username: cG9zdGdyZXM=  # Base64 encoded 'postgres'
  password: Q3B0LnByaWNlIysyMTg=  # Base64 encoded 'Cpt.price#+218'
  
---
apiVersion : v1
kind : ConfigMap
metadata:
  name : db-config
data:
  data:
  host: postgres-service
  dbName: softwareorganization
  port: "5432"  # Add the correct port number

